version: '3.1'

services:
  pg_db:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=kozlov-one-love
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cheapshot
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - 47543:5432
  service:
    image: nickkozlov/cheapexp:1.4.6
    restart: always
    ports:
      - 9000:80
  metabase:
    image: metabase/metabase:latest
    ports:
      - 4000:3000
    environment: 
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: cheapshot
      MB_DB_PORT: 47543
      MB_DB_USER: postgres
      MB_DB_PASS: kozlov-one-love
      MB_DB_HOST: pg_db
    depends_on: 
      - pg_db
      
volumes:
  pg_project: