version: '3.1'

services:
  pg_db:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=kozlov-one-love
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cheapshot
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - 47543:5432
  service:
    image: nickkozlov/cheapexp:1.0.6
    restart: always
    ports:
      - 9000:80
      
volumes:
  pg_project: