version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=kozlov-one-love
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cheapshot
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080